http:
  encoding.charset: UTF-8
  encoding.enable: true
  encoding.force: true

web:
  agent:
    predicate-name: gh-wr
springdoc:
  model-and-view-allowed: true
  api-docs:
    title: 报表服务api接口文档
    description: 报表服务api接口文档
    terms-of-service: https://github.com/ghuan
