server:
  port: 1001
springdoc:
  model-and-view-allowed: true
gh-api-doc:
  title: 报表服务api接口文档
  description: 报表服务api接口文档
  terms-of-service: https://github.com/ghuan
gh-jasperreports:
  ## 报表px图片所在服务地址，用于报表px图片地址修正
  px-image-server-address: http://localhost:1001/