server:
  port: 1000
springdoc:
  group-configs:
    - group: '用户模块'
      paths-to-match: '/user/**'
    - group: '用户模块1'
      paths-to-match: '/user1/**'
knife4j:
  enable: true
  documents:
    - name: 标题1
      locations: classpath:markdown/*
      group: all
    - name: 标题2
      locations: classpath:markdown1/*
      group: 用户模块
  basic:
    enable: false
    username: zhangsan
    password: lisi

gh-api-doc:
  title: 测试api接口文档
  description: 在线测试api接口文档
  terms-of-service: https://github.com/ghuan
