server:
  port: 1001
  profiles:
    active: dev
springdoc:
  model-and-view-allowed: true
  api-docs:
    title: 报表服务api接口文档
    description: 报表服务api接口文档
    terms-of-service: https://github.com/ghuan
